services:
  - type: web
    name: clean-dopamine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python youtube-vid-gen.py
    envVars:
      - key: YOUTUBE_API_KEY
        value: ${YOUTUBE_API_KEY}
      - key: TWILIO_AUTH_TOKEN
        value: ${TWILIO_AUTH_TOKEN}
      - key: TWILIO_ACCOUNT_SID
        value: ${TWILIO_ACCOUNT_SID}
      - key: TWILIO_PHONE_NUMBER
        value: ${TWILIO_PHONE_NUMBER}
 